import { UuidIdGenerator } from './uuid-id-generator';

// Canonical RFC 4122 UUID v4 layout:
//   xxxxxxxx-xxxx-4xxx-Yxxx-xxxxxxxxxxxx
// where Y is one of 8, 9, a, or b (the variant bits 10xx).
const UUID_V4_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

describe('UuidIdGenerator', () => {
  describe('IdGenerator port conformance', () => {
    it('implements the IdGenerator port', () => {
      const generator = new UuidIdGenerator();
      expect(typeof generator.nextId).toBe('function');
    });
  });

  describe('nextId()', () => {
    it('returns a string', () => {
      const generator = new UuidIdGenerator();
      const id = generator.nextId();

      expect(typeof id).toBe('string');
    });

    it('returns a UUID v4 in the canonical 8-4-4-4-12 layout', () => {
      const generator = new UuidIdGenerator();
      const id = generator.nextId();

      expect(id).toMatch(UUID_V4_REGEX);
    });

    it('returns 36 characters long', () => {
      const generator = new UuidIdGenerator();
      const id = generator.nextId();

      // 8 + 4 + 4 + 4 + 12 + 4 dashes = 36
      expect(id).toHaveLength(36);
    });

    it('returns a unique value across calls', () => {
      const generator = new UuidIdGenerator();
      const ids = new Set<string>();

      for (let i = 0; i < 1000; i++) {
        ids.add(generator.nextId());
      }

      // 1000 random UUIDs must produce 1000 distinct values; collisions in
      // UUID v4 at this volume would be a critical bug in the generator.
      expect(ids.size).toBe(1000);
    });

    it('returns values that are valid across many invocations', () => {
      const generator = new UuidIdGenerator();

      for (let i = 0; i < 100; i++) {
        const id = generator.nextId();
        expect(id).toMatch(UUID_V4_REGEX);
      }
    });
  });

  describe('instance isolation', () => {
    it('two generators produce non-overlapping IDs', () => {
      const a = new UuidIdGenerator();
      const b = new UuidIdGenerator();

      const fromA = new Set<string>();
      const fromB = new Set<string>();

      for (let i = 0; i < 100; i++) {
        fromA.add(a.nextId());
        fromB.add(b.nextId());
      }

      // With overwhelming probability, no UUID v4 generated by `a` should
      // match one generated by `b` in 100 draws. (Same property holds for
      // a single instance, but the cross-instance version catches any
      // shared static state bug.)
      for (const id of fromA) {
        expect(fromB.has(id)).toBe(false);
      }
    });
  });
});
