/**
 * Stable machine-readable error codes used by domain/application errors and
 * mapped to the API error envelope described in wiki/api/mvp-api-contract.md.
 */
export const ErrorCode = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_VALUE: 'INVALID_VALUE',
  INVALID_STATE: 'INVALID_STATE',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  PAYMENT_TOTAL_MISMATCH: 'PAYMENT_TOTAL_MISMATCH',
  CREDIT_CUSTOMER_REQUIRED: 'CREDIT_CUSTOMER_REQUIRED',
  IMMUTABLE_DOCUMENT: 'IMMUTABLE_DOCUMENT',
  DUPLICATE_NUMBER: 'DUPLICATE_NUMBER',
  DUPLICATE_SKU: 'DUPLICATE_SKU',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  CONCURRENT_MODIFICATION: 'CONCURRENT_MODIFICATION',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
